Demand Navigator/src/objects/Configuration_Setting__c.object
<CustomObject>
    <fields>
        <fullName>Stage__c</fullName>
        <description>Choose the Fiscal Year for Backlog calculation</description>
        <inlineHelpText>This is Help text</inlineHelpText>
        <label>Stage</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>FCST Configuration Setting</label>
    <nameField>
        <label>Configuration Setting Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>FCST Configuration Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Demand Navigator/src/objects/Demand_Configuration_Ratio__c.object
<CustomObject>
    <fields>
        <fullName>Business_Unit__c</fullName>
        <label>Business Unit</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Americas</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Central Europe</fullName>
                </value>
                <value>
                    <fullName>UK and Ireland</fullName>
                </value>
                <value>
                    <fullName>AMEA</fullName>
                </value>
                <value>
                    <fullName>Australia</fullName>
                </value>
                <value>
                    <fullName>Nordics</fullName>
                </value>
                <value>
                    <fullName>South and West Europe</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Division__c</fullName>
        <label>Industry</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Business_Unit__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Manufacturing</fullName>
                </value>
                <value>
                    <fullName>Banking and Finance</fullName>
                </value>
                <value>
                    <fullName>Healthcare</fullName>
                </value>
                <value>
                    <fullName>High Tech</fullName>
                </value>
                <value>
                    <fullName>Retail</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Offshore_Deal_Month__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Offshore Hours / Month</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Offshore_Resource__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Offshore Resource Ratio</label>
        <precision>10</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Onsite_Deal_Month__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Onsite Hours / Month</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Onsite_Resource__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Onsite Resource Ratio</label>
        <precision>10</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Demand Configuration Ratio</label>
    <nameField>
        <label>Demand Configuration Ratio Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Demand Configuration Ratios</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Demand Navigator/src/objects/Fiscal_Year_Model__c.object
<CustomObject>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Fiscal_Quarter__c</fullName>
        <label>Fiscal Quarter</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Fiscal_Year__c</fullName>
        <label>Fiscal Year</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Period_Name__c</fullName>
        <label>Period Name</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Period_Number__c</fullName>
        <label>Period Number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Record_Source__c</fullName>
        <label>Record Source</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>FCST Planning Fiscal Year</label>
    <nameField>
        <label>Planning Fiscal Year Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>FCST Planning Fiscal Years</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Demand Navigator/src/objects/Fiscal_Year_Planning__c.object
<CustomObject>
    <fields>
        <fullName>EndDate__c</fullName>
        <label>EndDate</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Record_Source__c</fullName>
        <label>Record Source</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>StartDate__c</fullName>
        <label>StartDate</label>
        <type>Date</type>
    </fields>
    <label>FCST Fiscal Year List</label>
    <nameField>
        <label>Fiscal Year List Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>FCST Fiscal Year Lists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Demand Navigator/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Budget_Planning_Version__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Budget Planning Version</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Planning_Version__c.Is_this_a_Budget_Planning_Version__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <infoMessage>Value does not exist or does not match filter criteria.</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Planning_Version__c</referenceTo>
        <relationshipLabel>Opportunities (Budget Planning Version)</relationshipLabel>
        <relationshipName>Opportunities2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Deal_Duration__c</fullName>
        <label>Deal Duration(months)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Deal_TCV__c</fullName>
        <label>Deal TCV $</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Division__c</fullName>
        <label>Industry</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>BussinessUnit__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Manufacturing</fullName>
                </value>
                <value>
                    <fullName>Banking and Finance</fullName>
                </value>
                <value>
                    <fullName>Healthcare</fullName>
                </value>
                <value>
                    <fullName>High Tech</fullName>
                </value>
                <value>
                    <fullName>Retail</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Offshore_Deal_Month__c</fullName>
        <label>Offshore Deal / Month</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Offshore_Resource__c</fullName>
        <label>Offshore Resource</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Onsite_Deal_Month__c</fullName>
        <label>Onsite Deal / Month</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Onsite_Resource__c</fullName>
        <label>Onsite Resource</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Planning_Version__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>FCST Planning Version</label>
        <referenceTo>Planning_Version__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project_Start_Date__c</fullName>
        <label>Project Start Date</label>
        <type>Date</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Demand Navigator/src/objects/Planning_Financial_Measure__c.object
<CustomObject>
    <fields>
        <fullName>Automatically_Calculated__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Automatically Calculated</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Measure_Description__c</fullName>
        <description>Description and explanation of how the Financial Measure is used in Planning activities</description>
        <label>Measure Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Measure_Type__c</fullName>
        <description>Measure type will influence how the value is used in calculations and reporting</description>
        <label>Measure Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Income</fullName>
                </value>
                <value>
                    <fullName>Expense</fullName>
                </value>
                <value>
                    <fullName>Asset</fullName>
                </value>
                <value>
                    <fullName>Liability</fullName>
                </value>
                <value>
                    <fullName>KPI</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Record_Source__c</fullName>
        <label>Record Source</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Restricted_by_Revenue_Term__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Restricted by Revenue Term</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Unit_of_Measure__c</fullName>
        <label>Unit of Measure</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Currency</fullName>
                </value>
                <value>
                    <fullName>Percentage</fullName>
                </value>
                <value>
                    <fullName>FTE</fullName>
                </value>
                <value>
                    <fullName>Quantity</fullName>
                </value>
                <value>
                    <fullName>Days</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>FCST Planning Measure</label>
    <nameField>
        <label>Planning Measure Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>FCST Planning Measures</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Demand Navigator/src/objects/Planning_Version__c.object
<CustomObject>
    <fields>
        <fullName>Data_Entry_Closed_Date__c</fullName>
        <label>Data Entry Closed Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Data_Entry_Start_Date__c</fullName>
        <label>Data Entry Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Fiscal_Year_Planning__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Fiscal Year Planning</label>
        <referenceTo>Fiscal_Year_Planning__c</referenceTo>
        <relationshipName>Planning_Versions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Is_this_a_Budget_Planning_Version__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is this a Budget Planning Version?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>MonthName__c</fullName>
        <label>MonthName</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Planning_Version_Current_Period__c</fullName>
        <label>Planning Version Current Period</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Planning_Version_Fiscal_Year__c</fullName>
        <label>Planning Version Fiscal Year</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Record_Source__c</fullName>
        <label>Record Source</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SequenceNo__c</fullName>
        <label>Sequence Number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Version_Status__c</fullName>
        <label>Version Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not Open</fullName>
                </value>
                <value>
                    <fullName>Open (Admin)</fullName>
                </value>
                <value>
                    <fullName>Open (User)</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>FCST Planning Version</label>
    <nameField>
        <label>Planning Version Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>FCST Planning Versions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Demand Navigator/src/classes/Test_Utility.cls
public with sharing class Test_Utility {
    public static final String USER_PROFILE_NAME = 'System Administrator';   
    public static User createUser(){
    	Profile p;
    	if (Schema.sObjectType.Profile.fields.Id.isAccessible()){
         p = [SELECT Id FROM Profile WHERE Name=: USER_PROFILE_NAME ]; 
    	}
        UserRole Pr = new UserRole(Name = 'Backlog Adjustment');
        if(UserRole.SObjectType.getDescribe().isCreateable()){
       	 insert Pr;
        }
        User pu = new User(Alias = 'standt11', Email='test138th_1@testorg.com', 
        EmailEncodingKey='UTF-8', LastName='Testinssg', LanguageLocaleKey='en_US', 
        LocaleSidKey='en_US', ProfileId = p.Id, UserRoleId = pr.Id,
        TimeZoneSidKey='America/Los_Angeles', UserName='test1s8th_1@testorg.com');  
        if(User.SObjectType.getDescribe().isCreateable()){
        insert pu;
        }
        
        
        UserRole r = new UserRole(Name = 'Backlog',ParentRoleId = Pr.Id);
        if(UserRole.SObjectType.getDescribe().isCreateable()){  
        insert r;
        }
        User u = new User(Alias = 'standt', Email='test18th_1@testorg.com', 
        EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
        LocaleSidKey='en_US', ProfileId = p.Id, UserRoleId = r.Id,
        TimeZoneSidKey='America/Los_Angeles', UserName='test18th_1@testorg.com');
        if(User.SObjectType.getDescribe().isCreateable()){  
        insert u;
        }
        
        return pu;  
    }
    public static List<Fiscal_Year_Planning__c> createFiscalYear(List<string> lstYears){
        List<Fiscal_Year_Planning__c> lstFY = new List<Fiscal_Year_Planning__c>();
        for(string syear : lstYears){
            Date fstartDate = Date.newInstance(Integer.valueOf(syear),1,1);
            Date fendDate = Date.newInstance(Integer.valueOf(syear),12,31);
            lstFY.add(new Fiscal_Year_Planning__c(Name = syear,StartDate__c = fstartDate,EndDate__c = fendDate));
        }
        return lstFY;
    }
    public static Account createAccount(){
        Account Acc = new Account(Name = 'Test Account');
        return Acc;
    }
    public static Configuration_Setting__c createConfigurationSettingObj(string cyear){
        Configuration_Setting__c con = new Configuration_Setting__c();
        con.Name = cyear;
        con.Stage__c = 'Open,Prospecting,ClosedWon,ClosedLost,Solutioning';
        return con;
        
    }
    public static Planning_Financial_Measure__c createMeasure(string mName){
        Planning_Financial_Measure__c FMObj = new Planning_Financial_Measure__c( 
        Name = mName,
        Automatically_Calculated__c= true , 
        Measure_Description__c = 'test',
        Measure_Type__c = 'Income',
        Record_Source__c = 'Installation',
        Unit_of_Measure__c = 'Currency',
        Restricted_by_Revenue_Term__c =false);
        return FMObj;
    }
    public static opportunity createOpportunity(string oppName, string AccId, string RT){
        
        Date FirstDate = Date.newInstance(2001,1,1);
        Date LastDate = Date.newInstance(2001,12,31);
        Date startpDate = System.today();
        Date endpDate = startpDate.addDays(30);
        
        Fiscal_Year_Planning__c fyp1 = new Fiscal_Year_Planning__c(Name = '2001',StartDate__c = FirstDate,EndDate__c = LastDate);
        if(Fiscal_Year_Planning__c.SObjectType.getDescribe().isCreateable()){
            
        insert fyp1;
         }
         List<Planning_Version__c>  listVersion = new List<Planning_Version__c>();
            for(Integer i = 1;i<13;i++){
            
                    listVersion.add(
                        new Planning_Version__c(
                            Fiscal_Year_Planning__c = fyp1.Id,
                            Is_this_a_Budget_Planning_Version__c = true,
                            SequenceNo__c = i,
                            Data_Entry_Closed_Date__c= endpDate ,
                            Data_Entry_Start_Date__c  = startpDate ,
                            Version_Status__c= 'Closed',
                            Planning_Version_Fiscal_Year__c = ((2000+i)+''),
                            Planning_Version_Current_Period__c= i+'',
                            MonthName__c = '5'
                        ));
                        startpDate  = endpDate.addDays(1);
                        endpDate = startpDate.addDays(30);
            } 
           if(Planning_Version__c.SObjectType.getDescribe().isCreateable()){
            
            insert listVersion;
           }
        //Id RTId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get(RT).getRecordTypeId();
        Opportunity Opp = new Opportunity(
            name = oppName,
            Deal_TCV__c = 100,
            accountId = AccId,
            Deal_Duration__c = 12,
            //RecordTypeId = RTId,
            Amount = 100,
            StageName='Open',
            Project_Start_Date__c = date.today(),
            CloseDate=date.today(),
            Budget_Planning_Version__c=listVersion[0].Id
        );
        return opp;
    }
    public static List<Fiscal_Year_Model__c> createFiscalYearPeriods(List<Fiscal_Year_Planning__c> lstFY)
    {
        List<Fiscal_Year_Model__c> lstFYP = new List<Fiscal_Year_Model__c>();       
        Integer q = 0;
        map<Integer,String> mapMonthString  = new map<Integer,String>();
        mapMonthString .put(1,'January');
        mapMonthString .put(2,'February');
        mapMonthString .put(3,'March');
        mapMonthString .put(4,'April');
        mapMonthString .put(5,'May');
        mapMonthString .put(6,'June');
        mapMonthString .put(7,'July');
        mapMonthString .put(8,'August');
        mapMonthString .put(9,'September');
        mapMonthString .put(10,'October');
        mapMonthString .put(11,'November');
        mapMonthString .put(12,'December');
        for(Fiscal_Year_Planning__c f : lstFY){
            Date startDate = f.StartDate__c;
            Date endDate = (startDate.addMonths(1)).adddays(-1);
            for(Integer i = 1;i<=12;i++){            
                if(i > 4)q= 1;
                else if(i > 7)q= 2;
                else if(i > 10)q= 3;
                else q = 4;
                lstFYP.add(
                    new Fiscal_Year_Model__c(
                    Name = 'FY'+f.Name+'P'+i,
                    End_Date__c = endDate,
                    Fiscal_Quarter__c = 'Q'+q,
                    Fiscal_Year__c = f.Name,
                    Period_Name__c = mapMonthString.get(i),
                    Period_Number__c = i,
                    Start_Date__c = startDate
                ));
                startDate  = startDate.addMonths(1);
                endDate = endDate.addMonths(1);
            }
        }
        return lstFYP;
    }
    public static Demand_Configuration_Ratio__c createDemandConfiguration(){
        Demand_Configuration_Ratio__c demand = new Demand_Configuration_Ratio__c();
        demand.Business_Unit__c = 'Americas';
        demand.Division__c = 'Manufacturing';
        demand.Offshore_Deal_Month__c = 10;
        demand.Offshore_Resource__c = 50;
        demand.Onsite_Deal_Month__c = 10;   
        demand.Onsite_Resource__c = 50;
        demand.Rate_per_Head_offshore__c = 20;  
        demand.Rate_per_Head_onsite__c = 20;
        demand.Service_Line__c = 'Applications'; 
        demand.OnSiteAmount__c = 'test1:20;test2:80';
        demand.OffshoreAmount__c = 'test1:20;test2:80';
        return demand;
    }
    public static List<Planning_Version__c> createPlanningVersion(List<Fiscal_Year_Planning__c> lstFY)
    {
        List<Planning_Version__c> lstFYP = new List<Planning_Version__c>();     
        Integer q = 0;
        map<Integer,String> mapMonthString  = new map<Integer,String>();
        mapMonthString .put(1,'January');
        mapMonthString .put(2,'February');
        mapMonthString .put(3,'March');
        mapMonthString .put(4,'April');
        mapMonthString .put(5,'May');
        mapMonthString .put(6,'June');
        mapMonthString .put(7,'July');
        mapMonthString .put(8,'August');
        mapMonthString .put(9,'September');
        mapMonthString .put(10,'October');
        mapMonthString .put(11,'November');
        mapMonthString .put(12,'December');
        for(Fiscal_Year_Planning__c f : lstFY){
            Date startDate = f.StartDate__c;
            Date endDate = (startDate.addMonths(1)).adddays(-1);
            for(Integer i = 1;i<=12;i++){            
                if(i > 4)q= 1;
                else if(i > 7)q= 2;
                else if(i > 10)q= 3;
                else q = 4;
                lstFYP.add(
                    new Planning_Version__c(
                    Is_this_a_Budget_Planning_Version__c = false,
                    Is_this_a_Gap_Planning_Version__c  = false,
                    SequenceNo__c = i,
                    Data_Entry_Closed_Date__c= endDate ,
                    Data_Entry_Start_Date__c  = startDate ,
                    Version_Status__c= 'Open(Admin)',
                    Planning_Version_Fiscal_Year__c = f.Name,
                    Planning_Version_Current_Period__c= i+'',
                    Fiscal_Year_Planning__c = f.Id,
                    MonthName__c = mapMonthString.get(i)
                    
                ));
                startDate  = startDate.addMonths(1);
                endDate = endDate.addMonths(1);
            }
        }
        return lstFYP;
    }
}