Demand Navigator/src/objects/Configuration_Setting__c.object
<CustomObject>
    <fields>
        <fullName>Stage__c</fullName>
        <description>Choose the Fiscal Year for Backlog calculation</description>
        <inlineHelpText>This is Help text</inlineHelpText>
        <label>Stage</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>FCST Configuration Setting</label>
    <nameField>
        <label>Configuration Setting Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>FCST Configuration Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Demand Navigator/src/objects/Demand_Configuration_Ratio__c.object
<CustomObject>
    <fields>
        <fullName>Demand_Key__c</fullName>
        <formula>TEXT(Business_Unit__c) &amp; &apos;-&apos; &amp;  TEXT(Division__c) &amp; &apos;-&apos; &amp;  TEXT(Service_Line__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Demand Key</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Emails__c</fullName>
        <label>Email Alerts</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Offshore_Deal_Month__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Offshore Hours / Month</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Offshore_Ratio__c</fullName>
        <formula>Offshore_Resource__c / Total_Deal__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Offshore Revenue Ratio</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Offshore_Resource__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Offshore Resource Ratio</label>
        <precision>10</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Onsite_Deal_Month__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Onsite Hours / Month</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Onsite_Ratio__c</fullName>
        <formula>Onsite_Resource__c /  Total_Deal__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Onsite Revenue Ratio</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Onsite_Resource__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Onsite Resource Ratio</label>
        <precision>10</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Rate_per_Head_offshore__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Rate per Head offshore</label>
        <precision>12</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Rate_per_Head_onsite__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Rate per Head onsite</label>
        <precision>12</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_Deal__c</fullName>
        <formula>Deal_offshore__c + Deal_onsite__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Total Deal</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Demand Configuration Ratio</label>
    <nameField>
        <label>Demand Configuration Ratio Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Demand Configuration Ratios</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Demand Navigator/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Demand_Key__c</fullName>
        <formula>TEXT(BussinessUnit__c) &amp;&apos;-&apos;&amp; TEXT(Division__c) &amp;&apos;-&apos;&amp; TEXT(Service_Line__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Demand Key</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Offshore_Deal_Month__c</fullName>
        <label>Offshore Deal / Month</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Offshore_Ratio__c</fullName>
        <formula>Offshore_Resource__c / Total_Deal__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Offshore Ratio</label>
        <precision>18</precision>
        <scale>8</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Offshore_Resource__c</fullName>
        <label>Offshore Resource</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Onsite_Deal_Month__c</fullName>
        <label>Onsite Deal / Month</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Onsite_Ratio__c</fullName>
        <formula>Onsite_Resource__c / Total_Deal__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Onsite Ratio</label>
        <precision>18</precision>
        <scale>8</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Onsite_Resource__c</fullName>
        <label>Onsite Resource</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Planning_Version__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>FCST Planning Version</label>
        <referenceTo>Planning_Version__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Rate_per_Head_offshore__c</fullName>
        <label>Rate per Head offshore</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Rate_per_Head_onsite__c</fullName>
        <label>Rate per Head onsite</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_Deal__c</fullName>
        <formula>Deal_onsite__c + Deal_offshore__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Total Deal</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_Resource__c</fullName>
        <formula>Onsite_Resource__c + Offshore_Resource__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Total Resource</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Demand Navigator/src/objects/Planning_Model__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>Planning_Models</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Planning_Version__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Planning Version</label>
        <referenceTo>Planning_Version__c</referenceTo>
        <relationshipName>Planning_Models</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>FCST Planning Model</label>
    <nameField>
        <displayFormat>M-{000000}</displayFormat>
        <label>Planning Model Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>FCST Planning Models</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Demand Navigator/src/objects/Planning_Version__c.object
<CustomObject>
    <label>FCST Planning Version</label>
    <nameField>
        <label>Planning Version Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>FCST Planning Versions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Demand Navigator/src/classes/OpportunityEmailService.cls
public with sharing class OpportunityEmailService{
    public static void sendEmail(List<Opportunity> lstNewOpportunity){
        set<Id> setIds = new set<Id>();
        for(Opportunity opp: lstNewOpportunity){
            setIds.add(opp.Id);
        }
        sendAttachment(setIds);
    }
    //@Future(callout=true)
    public static void sendAttachment(set<Id> setIds){   
        set<Id> setVersions = new set<Id>();
        map<Id,string> mapVersionNames = new map<Id,string>();
        List<Opportunity> lstNewOpportunity;
        if (Schema.sObjectType.Planning_Model__c.fields.Planning_Version__c.isAccessible() && Schema.sObjectType.Planning_Model__c.fields.Id.isAccessible()
        && Schema.sObjectType.Planning_Version__c.fields.Name.isAccessible()
        && Schema.sObjectType.Opportunity.fields.Id.isAccessible() && Schema.sObjectType.Opportunity.fields.Name.isAccessible()
        && Schema.sObjectType.Opportunity.fields.StageName.isAccessible() && Schema.sObjectType.Opportunity.fields.Demand_Key__c.isAccessible() 
        && Schema.sObjectType.Opportunity.fields.Onsite_Resource__c.isAccessible() && Schema.sObjectType.Opportunity.fields.Rate_per_Head_onsite__c.isAccessible()
        && Schema.sObjectType.Opportunity.fields.Rate_per_Head_onsite__c.isAccessible() && Schema.sObjectType.Opportunity.fields.Onsite_Deal_Month__c.isAccessible()
        && Schema.sObjectType.Opportunity.fields.onsite_Ratio__c.isAccessible() && Schema.sObjectType.Opportunity.fields.Offshore_Resource__c.isAccessible()
        && Schema.sObjectType.Opportunity.fields.Rate_per_Head_offshore__c.isAccessible() && Schema.sObjectType.Opportunity.fields.Offshore_Deal_Month__c.isAccessible()
        && Schema.sObjectType.Opportunity.fields.Offshore_Ratio__c.isAccessible() && Schema.sObjectType.Opportunity.fields.Total_Resource__c.isAccessible()
        && Schema.sObjectType.Opportunity.fields.Total_Deal__c.isAccessible()){
        	lstNewOpportunity = [select Id,Name,(select Id,Planning_Version__r.Name,Planning_Version__c from Planning_Models__r order by Planning_Version__r.Name),StageName,Demand_Key__c,Onsite_Resource__c,Rate_per_Head_onsite__c,Onsite_Deal_Month__c,onsite_Ratio__c,Offshore_Resource__c,Rate_per_Head_offshore__c,Offshore_Deal_Month__c,Offshore_Ratio__c,Total_Resource__c,Total_Deal__c from Opportunity where Id IN: setIds];
        }
        set<string> ConfigStages = new set<string>();
        if (Schema.sObjectType.Configuration_Setting__c.fields.Id.isAccessible() && Schema.sObjectType.Configuration_Setting__c.fields.Stage__c.isAccessible()){
	        for(Configuration_Setting__c cs : [select Id,Stage__c from Configuration_Setting__c limit 1]){
	            if(cs.Stage__c <> null)
	            for(string s : cs.Stage__c.split(',')){
	                ConfigStages.add(s);
	            }           
	        }
        }
        map<string,Demand_Configuration_Ratio__c> mapDemandKey = new map<string,Demand_Configuration_Ratio__c>();
        map<Id,Set<Id>> mapOppVersions = new map<Id,set<Id>>();
        for(Opportunity opp: lstNewOpportunity){
            if(ConfigStages.contains(opp.StageName))
                mapDemandKey.put(opp.Demand_Key__c,null);
            
            setVersions.clear();
            for(Planning_Model__c m : opp.Planning_Models__r){
                setVersions.add(m.Planning_Version__c);
                mapVersionNames.put(m.Planning_Version__c,m.Planning_Version__r.Name);
            }
            mapOppVersions.put(opp.Id,setVersions);
            
        }    
        if (Schema.sObjectType.Demand_Configuration_Ratio__c.fields.Id.isAccessible() && Schema.sObjectType.Demand_Configuration_Ratio__c.fields.Demand_Key__c.isAccessible()
        && Schema.sObjectType.Demand_Configuration_Ratio__c.fields.Emails__c.isAccessible()){ 
	        for(Demand_Configuration_Ratio__c dcr : [select Id,Demand_Key__c, Emails__c from Demand_Configuration_Ratio__c 
	        where Demand_Key__c in: mapDemandKey.keyset()]){
	            mapDemandKey.put(dcr.Demand_Key__c, dcr);
	        }
        }      
        List<Messaging.SingleEmailMessage> lstMail = new List<Messaging.SingleEmailMessage>();
        
        for(Opportunity opp: lstNewOpportunity){
            if(mapDemandKey.containsKey(opp.Demand_Key__c ) && mapDemandKey.get(opp.Demand_Key__c ) <> null){
                
                if(mapOppVersions.containsKey(opp.Id)){
                    
                    string strEmailTB = '';
                    string strEmailCSV = '';
     
                    Demand_Configuration_Ratio__c conf = mapDemandKey.get(opp.Demand_Key__c );
                    string DCREmail = conf.Emails__c;
                    String EmailBody = 'Hi,<br/><br/>'+opp.Name+' is updated by Stage '+opp.StageName+' for following demand configuration information.<div>   <table><tr><td><table><tr><td>Onsite Resource Ratio</td><td>'+opp.Onsite_Resource__c+'</td></tr><tr><td>Onsite rate per head</td><td>'+opp.Rate_per_Head_onsite__c+'</td> </tr><tr><td>Onsite Hours / Month</td><td>'+opp.Onsite_Deal_Month__c+'</td></tr><tr><td>Onsite Revenue Ratio</td><td>'+opp.Onsite_Ratio__c+'</td></tr></table></td><td><table><tr><td>Offshore Resource Ratio</td>   <td>'+opp.Offshore_Resource__c+'</td></tr><tr><td>Offshore rate per head</td><td>'+opp.Rate_per_Head_offshore__c+'</td></tr><tr><td>Offshore Hours / Month</td><td>'+opp.Offshore_Deal_Month__c+'</td></tr><tr><td>Offshore Revenue Ratio</td><td>'+opp.Offshore_Ratio__c+'</td></tr></table></td></tr><tr><td>Total Resource : '+opp.Total_Resource__c+'</td><td>total Deal : '+opp.Total_Deal__c+'</td></tr></table></div><br/>';


                        
                    for(Id vId : mapOppVersions.get(opp.Id)){
                        DemandUtility dobj = new DemandUtility(opp.Id,vId);
                        List<FiscalYear> lstTFModel = dobj.lstFModel;
                        
                        strEmailTB += dobj.getDemandData(lstTFModel,mapVersionNames.get(vId))+'<br/><br/>';
                        strEmailCSV += dobj.getDemandCSV(lstTFModel,mapVersionNames.get(vId))+'\n\n';
                    }
                    
                    if(DCREmail <> null){
                        List<string> lstEmails = new List<String>();
                        for(string s: DCREmail.split(';'))
                            lstEmails.add(s);
                        //lstEmails.clear();
                       // lstEmails.add('skhabimoonmca@gmail.com');
                        if(lstEmails.size()>0){

                            // Create the email attachment
                            Messaging.EmailFileAttachment efa = new Messaging.EmailFileAttachment();
                            efa.setFileName('DemandForcecaseReport.csv');
                            efa.setBody(Blob.valueOf (strEmailCSV));

                            Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
                            mail.setToAddresses(lstEmails);
                            mail.setSenderDisplayName('Salesforce Support');
                            mail.setSubject('Opportunity Stage Updated');
                            mail.setUseSignature(true);
                            mail.setHtmlBody(EmailBody+strEmailTB);
                            //mail.setHtmlBody(EmailBody);
                            mail.setFileAttachments(new Messaging.EmailFileAttachment[] {efa});
                            lstMail.add(mail);
                        }
                    }
                }
                
            }
            
        }
        
        if(lstMail.size()>0){
           //Messaging.sendEmail(lstMail);
           try{Messaging.sendEmail(lstMail);}catch(Exception e){}
        }
    }
    
   
}