Demand Navigator/src/objects/Configuration_Setting__c.object
<CustomObject>
    <label>FCST Configuration Setting</label>
    <nameField>
        <label>Configuration Setting Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>FCST Configuration Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Demand Navigator/src/objects/Demand_Configuration_Ratio__c.object
<CustomObject>
    <fields>
        <fullName>Division__c</fullName>
        <label>Industry</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Business_Unit__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Manufacturing</fullName>
                </value>
                <value>
                    <fullName>Banking and Finance</fullName>
                </value>
                <value>
                    <fullName>Healthcare</fullName>
                </value>
                <value>
                    <fullName>High Tech</fullName>
                </value>
                <value>
                    <fullName>Retail</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Service_Line__c</fullName>
        <label>Offering</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Applications</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Cloud</fullName>
                </value>
                <value>
                    <fullName>Consulting</fullName>
                </value>
                <value>
                    <fullName>Cyber</fullName>
                </value>
                <value>
                    <fullName>Infrastructure</fullName>
                </value>
                <value>
                    <fullName>Big Data</fullName>
                </value>
                <value>
                    <fullName>Mobility</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Demand Configuration Ratio</label>
    <nameField>
        <label>Demand Configuration Ratio Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Demand Configuration Ratios</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Demand Navigator/src/objects/Fiscal_Year_Model__c.object
<CustomObject>
    <label>FCST Planning Fiscal Year</label>
    <nameField>
        <label>Planning Fiscal Year Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>FCST Planning Fiscal Years</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Demand Navigator/src/objects/Fiscal_Year_Planning__c.object
<CustomObject>
    <label>FCST Fiscal Year List</label>
    <nameField>
        <label>Fiscal Year List Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>FCST Fiscal Year Lists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Demand Navigator/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>BussinessUnit__c</fullName>
        <label>BussinessUnit</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Americas</fullName>
                </value>
                <value>
                    <fullName>Central Europe</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>UK and Ireland</fullName>
                </value>
                <value>
                    <fullName>AMEA</fullName>
                </value>
                <value>
                    <fullName>Australia</fullName>
                </value>
                <value>
                    <fullName>Nordics</fullName>
                </value>
                <value>
                    <fullName>South and West Europe</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Division__c</fullName>
        <label>Industry</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>BussinessUnit__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Manufacturing</fullName>
                </value>
                <value>
                    <fullName>Banking and Finance</fullName>
                </value>
                <value>
                    <fullName>Healthcare</fullName>
                </value>
                <value>
                    <fullName>High Tech</fullName>
                </value>
                <value>
                    <fullName>Retail</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Planning_Version__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>FCST Planning Version</label>
        <referenceTo>Planning_Version__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Service_Line__c</fullName>
        <label>Offering</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Applications</fullName>
                </value>
                <value>
                    <fullName>Cloud</fullName>
                </value>
                <value>
                    <fullName>Consulting</fullName>
                </value>
                <value>
                    <fullName>Cyber</fullName>
                </value>
                <value>
                    <fullName>Infrastructure</fullName>
                </value>
                <value>
                    <fullName>Big Data</fullName>
                </value>
                <value>
                    <fullName>Mobility</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Budget</fullName>
        <active>true</active>
        <businessProcess>Forecast Budget Process</businessProcess>
        <label>Budget</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Demand Navigator/src/objects/Planning_Financial_Measure__c.object
<CustomObject>
    <label>FCST Planning Measure</label>
    <nameField>
        <label>Planning Measure Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>FCST Planning Measures</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Demand Navigator/src/objects/Planning_Version__c.object
<CustomObject>
    <fields>
        <fullName>Fiscal_Year_Planning__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Fiscal Year Planning</label>
        <referenceTo>Fiscal_Year_Planning__c</referenceTo>
        <relationshipName>Planning_Versions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>FCST Planning Version</label>
    <nameField>
        <label>Planning Version Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>FCST Planning Versions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Demand Navigator/src/classes/Test_DemandForcecaseCSV.cls
@isTest 
private with sharing class Test_DemandForcecaseCSV{
    static testMethod void unitTest() {
        
        
        
        User loginUser = Test_Utility.createUser(); 
        system.runAs(loginUser)
        {       
            
            List<string> lstYearNames = new List<string>();
            lstYearNames.add('2016');
            lstYearNames.add('2017');
            lstYearNames.add('2018');
            List<Fiscal_Year_Planning__c> lstPYear = Test_Utility.createFiscalYear(lstYearNames);
              if(Fiscal_Year_Planning__c.SObjectType.getDescribe().isCreateable()){
           		 insert lstPYear;
              }
            
            List<Fiscal_Year_Model__c> lstPYearPeriod = Test_Utility.createFiscalYearPeriods(lstPYear);
            if(Fiscal_Year_Model__c.SObjectType.getDescribe().isCreateable()){
           	 insert lstPYearPeriod;
            }
            
            
            List<Planning_Version__c> lstPVersion = Test_Utility.createPlanningVersion(lstPYear);
            if(Planning_Version__c.SObjectType.getDescribe().isCreateable()){
            	insert lstPVersion;
            }
            
            Planning_Financial_Measure__c measureObj1 = Test_Utility.createMeasure('Revenue');
            if(Planning_Financial_Measure__c.SObjectType.getDescribe().isCreateable()){
            insert measureObj1;
            }
            Planning_Financial_Measure__c measureObj2 = Test_Utility.createMeasure('Revenue Backlog');
            if(Planning_Financial_Measure__c.SObjectType.getDescribe().isCreateable()){
            insert measureObj2;
            }
            Planning_Financial_Measure__c measureObj3 = Test_Utility.createMeasure('Onsite');
             if(Planning_Financial_Measure__c.SObjectType.getDescribe().isCreateable()){
            insert measureObj3;
             }
            Planning_Financial_Measure__c measureObj4 = Test_Utility.createMeasure('Offshore');
             if(Planning_Financial_Measure__c.SObjectType.getDescribe().isCreateable()){
            insert measureObj4;
             }
            
            Configuration_Setting__c configObj = Test_Utility.createConfigurationSettingObj('2018');
             if(Configuration_Setting__c.SObjectType.getDescribe().isCreateable()){
           		 insert configObj;
             }
            
            Account Acc = Test_Utility.createAccount();
            if(Account.SObjectType.getDescribe().isCreateable()){
            insert Acc;
            }
            system.assertNotEquals(Acc.Id,null);
            
            //Opportunity Opp = Test_Utility.createOpportunity('Test Opp',Acc.Id,'Regular');
            Opportunity Opp = Test_Utility.createOpportunity('Test Opp',Acc.Id,'Budget');
            Opp.BussinessUnit__c = 'Americas';
            Opp.Division__c = 'Manufacturing';
            Opp.Service_Line__c = 'Applications'; 
             if(Opportunity.SObjectType.getDescribe().isCreateable()){
            insert Opp;
             }
            
            Demand_Configuration_Ratio__c  demand = Test_Utility.createDemandConfiguration();
            if(Demand_Configuration_Ratio__c.SObjectType.getDescribe().isCreateable()){
            insert demand;
            }
             User cUser;
             if (Schema.sObjectType.User.fields.Id.isAccessible() && Schema.sObjectType.User.fields.UserRoleId.isAccessible()){
              cUser = [select Id,UserRoleId from User where Id=: loginUser.id];
             }
            Test.StartTest();     
        
                PageReference pageRef = Page.DemandForcecaseCSV;
                pageRef.getParameters().put('id', String.valueOf(Opp.Id));
                Test.setCurrentPage(pageRef);
                DemandForcecaseCSV con = new DemandForcecaseCSV();
            Test.StopTest();
        }        
        
    }
}