Demand Navigator/src/objects/Demand_Configuration_Ratio__c.object
<CustomObject>
    <fields>
        <fullName>Demand_Key__c</fullName>
        <formula>TEXT(Business_Unit__c) &amp; &apos;-&apos; &amp;  TEXT(Division__c) &amp; &apos;-&apos; &amp;  TEXT(Service_Line__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Demand Key</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Offshore_Deal_Month__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Offshore Hours / Month</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Offshore_Resource__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Offshore Resource Ratio</label>
        <precision>10</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Onsite_Deal_Month__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Onsite Hours / Month</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Onsite_Resource__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Onsite Resource Ratio</label>
        <precision>10</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Rate_per_Head_offshore__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Rate per Head offshore</label>
        <precision>12</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Rate_per_Head_onsite__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Rate per Head onsite</label>
        <precision>12</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Demand Configuration Ratio</label>
    <nameField>
        <label>Demand Configuration Ratio Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Demand Configuration Ratios</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Demand Navigator/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Demand_Key__c</fullName>
        <formula>TEXT(BussinessUnit__c) &amp;&apos;-&apos;&amp; TEXT(Division__c) &amp;&apos;-&apos;&amp; TEXT(Service_Line__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Demand Key</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Offshore_Deal_Month__c</fullName>
        <label>Offshore Deal / Month</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Offshore_Resource__c</fullName>
        <label>Offshore Resource</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Onsite_Deal_Month__c</fullName>
        <label>Onsite Deal / Month</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Onsite_Resource__c</fullName>
        <label>Onsite Resource</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Rate_per_Head_offshore__c</fullName>
        <label>Rate per Head offshore</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Rate_per_Head_onsite__c</fullName>
        <label>Rate per Head onsite</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Demand Navigator/src/classes/DemandConfiguration.cls
public with sharing class DemandConfiguration{ 
    public static void updateDemandConfiguration(List<Opportunity> lstNewOpportunity){
      
        map<string,Demand_Configuration_Ratio__c> mapDemandKey = new map<string,Demand_Configuration_Ratio__c>();
        for(Opportunity opp: lstNewOpportunity){
            mapDemandKey.put(opp.Demand_Key__c,null);
        }    
         if (Schema.sObjectType.Demand_Configuration_Ratio__c.fields.Id.isAccessible() && Schema.sObjectType.Demand_Configuration_Ratio__c.fields.Demand_Key__c.isAccessible()
         && Schema.sObjectType.Demand_Configuration_Ratio__c.fields.Onsite_Resource__c.isAccessible() && Schema.sObjectType.Demand_Configuration_Ratio__c.fields.Rate_per_Head_onsite__c.isAccessible()
         && Schema.sObjectType.Demand_Configuration_Ratio__c.fields.offshore_Resource__c.isAccessible() && Schema.sObjectType.Demand_Configuration_Ratio__c.fields.Rate_per_Head_offshore__c.isAccessible()
         && Schema.sObjectType.Demand_Configuration_Ratio__c.fields.Onsite_Deal_Month__c.isAccessible() && Schema.sObjectType.Demand_Configuration_Ratio__c.fields.Offshore_Deal_Month__c.isAccessible()){
	        for(Demand_Configuration_Ratio__c dcr : [select Id,Demand_Key__c, Onsite_Resource__c,Rate_per_Head_onsite__c,
	        offshore_Resource__c,Rate_per_Head_offshore__c,Onsite_Deal_Month__c,Offshore_Deal_Month__c from Demand_Configuration_Ratio__c 
	        where Demand_Key__c in: mapDemandKey.keyset()]){
	            mapDemandKey.put(dcr.Demand_Key__c, dcr);
	        }
         }
        for(Opportunity opp: lstNewOpportunity){
            if(mapDemandKey.containsKey(opp.Demand_Key__c ) && mapDemandKey.get(opp.Demand_Key__c) <> null){
                Demand_Configuration_Ratio__c conf = mapDemandKey.get(opp.Demand_Key__c );
                opp.Onsite_Resource__c = conf.Onsite_Resource__c;
                opp.Rate_per_Head_onsite__c = conf.Rate_per_Head_onsite__c ;
                opp.offshore_Resource__c = conf.offshore_Resource__c;
                opp.Rate_per_Head_offshore__c= conf.Rate_per_Head_offshore__c;
                opp.Onsite_Deal_Month__c= conf.Onsite_Deal_Month__c;
                opp.Offshore_Deal_Month__c= conf.Offshore_Deal_Month__c;

            }
        }
    }
}