Demand Navigator/src/objects/Demand_Configuration_Ratio__c.object
<CustomObject>
    <fields>
        <fullName>Business_Unit__c</fullName>
        <label>Business Unit</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Americas</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Central Europe</fullName>
                </value>
                <value>
                    <fullName>UK and Ireland</fullName>
                </value>
                <value>
                    <fullName>AMEA</fullName>
                </value>
                <value>
                    <fullName>Australia</fullName>
                </value>
                <value>
                    <fullName>Nordics</fullName>
                </value>
                <value>
                    <fullName>South and West Europe</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Division__c</fullName>
        <label>Industry</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Business_Unit__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Manufacturing</fullName>
                </value>
                <value>
                    <fullName>Banking and Finance</fullName>
                </value>
                <value>
                    <fullName>Healthcare</fullName>
                </value>
                <value>
                    <fullName>High Tech</fullName>
                </value>
                <value>
                    <fullName>Retail</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>OffshoreAmount__c</fullName>
        <label>OffshoreAmount</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Offshore_Deal_Month__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Offshore Hours / Month</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Offshore_Resource__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Offshore Resource Ratio</label>
        <precision>10</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>OnSiteAmount__c</fullName>
        <label>OnSiteAmount</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Onsite_Deal_Month__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Onsite Hours / Month</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Onsite_Resource__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Onsite Resource Ratio</label>
        <precision>10</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Rate_per_Head_offshore__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Rate per Head offshore</label>
        <precision>12</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Rate_per_Head_onsite__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Rate per Head onsite</label>
        <precision>12</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Service_Line__c</fullName>
        <label>Offering</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Applications</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Cloud</fullName>
                </value>
                <value>
                    <fullName>Consulting</fullName>
                </value>
                <value>
                    <fullName>Cyber</fullName>
                </value>
                <value>
                    <fullName>Infrastructure</fullName>
                </value>
                <value>
                    <fullName>Big Data</fullName>
                </value>
                <value>
                    <fullName>Mobility</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Demand Configuration Ratio</label>
    <nameField>
        <label>Demand Configuration Ratio Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Demand Configuration Ratios</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Demand Navigator/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>BussinessUnit__c</fullName>
        <label>BussinessUnit</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Americas</fullName>
                </value>
                <value>
                    <fullName>Central Europe</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>UK and Ireland</fullName>
                </value>
                <value>
                    <fullName>AMEA</fullName>
                </value>
                <value>
                    <fullName>Australia</fullName>
                </value>
                <value>
                    <fullName>Nordics</fullName>
                </value>
                <value>
                    <fullName>South and West Europe</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Division__c</fullName>
        <label>Industry</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>BussinessUnit__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Manufacturing</fullName>
                </value>
                <value>
                    <fullName>Banking and Finance</fullName>
                </value>
                <value>
                    <fullName>Healthcare</fullName>
                </value>
                <value>
                    <fullName>High Tech</fullName>
                </value>
                <value>
                    <fullName>Retail</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Offshore_Deal_Month__c</fullName>
        <label>Offshore Deal / Month</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Offshore_Resource__c</fullName>
        <label>Offshore Resource</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Onsite_Deal_Month__c</fullName>
        <label>Onsite Deal / Month</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Onsite_Resource__c</fullName>
        <label>Onsite Resource</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Rate_per_Head_offshore__c</fullName>
        <label>Rate per Head offshore</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Rate_per_Head_onsite__c</fullName>
        <label>Rate per Head onsite</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Service_Line__c</fullName>
        <label>Offering</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Applications</fullName>
                </value>
                <value>
                    <fullName>Cloud</fullName>
                </value>
                <value>
                    <fullName>Consulting</fullName>
                </value>
                <value>
                    <fullName>Cyber</fullName>
                </value>
                <value>
                    <fullName>Infrastructure</fullName>
                </value>
                <value>
                    <fullName>Big Data</fullName>
                </value>
                <value>
                    <fullName>Mobility</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Budget</fullName>
        <active>true</active>
        <businessProcess>Forecast Budget Process</businessProcess>
        <label>Budget</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Demand Navigator/src/classes/Test_DemandConfiguration.cls
@isTest 
private with sharing class Test_DemandConfiguration{
    static testMethod void unitTest() {
        
        Demand_Configuration_Ratio__c demand = new Demand_Configuration_Ratio__c();
        demand.Business_Unit__c = 'Americas';
        demand.Division__c = 'Manufacturing';
        demand.Offshore_Deal_Month__c = 10;
        demand.Offshore_Resource__c = 50;
        demand.Onsite_Deal_Month__c = 10;   
        demand.Onsite_Resource__c = 50;
        demand.Rate_per_Head_offshore__c = 20;  
        demand.Rate_per_Head_onsite__c = 20;
        demand.Service_Line__c = 'Applications'; 
        demand.OnSiteAmount__c = 'test1:20;test2:80';
        demand.OffshoreAmount__c = 'test1:20;test2:80';
        if(Demand_Configuration_Ratio__c.SObjectType.getDescribe().isCreateable()){
         insert demand;
        }
        system.assertNotEquals(demand.Id,null);
        
        PageReference pageRef = Page.DemandConfiguration;
        pageRef.getParameters().put('id', String.valueOf(demand.Id));
        Test.setCurrentPage(pageRef);
        ApexPages.StandardController sc = new ApexPages.StandardController(demand);
        DemandConfigurationController con = new DemandConfigurationController(sc);
        con.getOnSiteOption();
        con.getOffShoreOption();        
        con.reset();
        con.saveDemandRatio(); 
        DemandConfigurationController.WOption empWObj = new DemandConfigurationController.WOption(true,'test1','Test2',42.5);
        con.lstOffshoreOption.add(empWObj);
       // con.lstOnsiteOption.add(empWObj);
    }
    static testmethod void demandconfig(){
        Account Acc = Test_Utility.createAccount();
         if(Account.SObjectType.getDescribe().isCreateable()){
        	insert Acc;
         }
        system.assertNotEquals(Acc.Id,null);
        
        Demand_Configuration_Ratio__c  demand = Test_Utility.createDemandConfiguration();
        if(Demand_Configuration_Ratio__c.SObjectType.getDescribe().isCreateable()){
        	insert demand;
        }
        
       // Opportunity Opp = Test_Utility.createOpportunity('Test Opp',Acc.Id,'Regular');
        Opportunity Opp = Test_Utility.createOpportunity('Test Opp',Acc.Id,'Budget');
        Opp.BussinessUnit__c = 'Americas';
        Opp.Division__c = 'Manufacturing';
        Opp.Service_Line__c = 'Applications'; 
         if(Opportunity.SObjectType.getDescribe().isCreateable()){
        	insert Opp;
         }
        
        
    }
}