Demand Navigator/src/objects/Fiscal_Year_Model__c.object
<CustomObject>
    <fields>
        <fullName>Fiscal_Quarter__c</fullName>
        <label>Fiscal Quarter</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>FCST Planning Fiscal Year</label>
    <nameField>
        <label>Planning Fiscal Year Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>FCST Planning Fiscal Years</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Demand Navigator/src/objects/Fiscal_Year_Planning__c.object
<CustomObject>
    <fields>
        <fullName>EndDate__c</fullName>
        <label>EndDate</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>StartDate__c</fullName>
        <label>StartDate</label>
        <type>Date</type>
    </fields>
    <label>FCST Fiscal Year List</label>
    <nameField>
        <label>Fiscal Year List Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>FCST Fiscal Year Lists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Demand Navigator/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>BussinessUnit__c</fullName>
        <label>BussinessUnit</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Americas</fullName>
                </value>
                <value>
                    <fullName>Central Europe</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>UK and Ireland</fullName>
                </value>
                <value>
                    <fullName>AMEA</fullName>
                </value>
                <value>
                    <fullName>Australia</fullName>
                </value>
                <value>
                    <fullName>Nordics</fullName>
                </value>
                <value>
                    <fullName>South and West Europe</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Deal_Duration__c</fullName>
        <label>Deal Duration(months)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Deal_TCV__c</fullName>
        <label>Deal TCV $</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Division__c</fullName>
        <label>Industry</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>BussinessUnit__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Manufacturing</fullName>
                </value>
                <value>
                    <fullName>Banking and Finance</fullName>
                </value>
                <value>
                    <fullName>Healthcare</fullName>
                </value>
                <value>
                    <fullName>High Tech</fullName>
                </value>
                <value>
                    <fullName>Retail</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Legacy__c</fullName>
        <label>Legacy</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>StageName</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>YES</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Planning_Version__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>FCST Planning Version</label>
        <referenceTo>Planning_Version__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project_Start_Date__c</fullName>
        <label>Project Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Service_Line__c</fullName>
        <label>Offering</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Applications</fullName>
                </value>
                <value>
                    <fullName>Cloud</fullName>
                </value>
                <value>
                    <fullName>Consulting</fullName>
                </value>
                <value>
                    <fullName>Cyber</fullName>
                </value>
                <value>
                    <fullName>Infrastructure</fullName>
                </value>
                <value>
                    <fullName>Big Data</fullName>
                </value>
                <value>
                    <fullName>Mobility</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Demand Navigator/src/objects/Planning_Financial_Measure__c.object
<CustomObject>
    <label>FCST Planning Measure</label>
    <nameField>
        <label>Planning Measure Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>FCST Planning Measures</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Demand Navigator/src/objects/Planning_Model__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Fiscal_Period__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Fiscal Period</label>
        <referenceTo>Fiscal_Year_Model__c</referenceTo>
        <relationshipName>Planning_Models</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>Planning_Models</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Planning_Measure__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Planning Measure</label>
        <referenceTo>Planning_Financial_Measure__c</referenceTo>
        <relationshipName>Planning_Models</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Planning_Version__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Planning Version</label>
        <referenceTo>Planning_Version__c</referenceTo>
        <relationshipName>Planning_Models</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>FCST Planning Model</label>
    <nameField>
        <displayFormat>M-{000000}</displayFormat>
        <label>Planning Model Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>FCST Planning Models</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Demand Navigator/src/objects/Planning_Version__c.object
<CustomObject>
    <fields>
        <fullName>Fiscal_Year_Planning__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Fiscal Year Planning</label>
        <referenceTo>Fiscal_Year_Planning__c</referenceTo>
        <relationshipName>Planning_Versions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>FCST Planning Version</label>
    <nameField>
        <label>Planning Version Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>FCST Planning Versions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Demand Navigator/src/classes/Bookings_PrioritizationController.cls
public with sharing class Bookings_PrioritizationController{

    private string strFromPlan;
    public string getstrFromPlan() {return strFromPlan;}
    public void setstrFromPlan(string s) {if(s<>null)strFromPlan= String.escapeSingleQuotes(s);}
    
    private string userCurrencySign;
    public string getuserCurrencySign(){return userCurrencySign;}  public void setuserCurrencySign(string u){ userCurrencySign= String.escapeSingleQuotes(u); }
    
    private string strE_FromPlan; public string getstrE_FromPlan() {return strE_FromPlan;}  public void setstrE_FromPlan(string s) {if(s<>null)strE_FromPlan= String.escapeSingleQuotes(s);}
    
    private string strAccOwner;   public string getstrAccOwner() {return strAccOwner;}    public void setstrAccOwner(string s) {if(s<>null)strAccOwner= String.escapeSingleQuotes(s);}
    
    public opportunity dummyOpportunity{get;set;}
    public Set<string> setUser{get;set;}
    
    String[] OppStages = new String[]{};
    public String[] getOppStages() { return OppStages; }    public void setOppStages(String[] OppStages) { this.OppStages = OppStages;  }   
   
    private String strFromPlanYear;public String getstrFromPlanYear(){return strFromPlanYear;}public void setstrFromPlanYear(string s){if(s<>null)strFromPlanYear= String.escapeSingleQuotes(s); }
    
      
    List<Data> chartData;  
    private string Category; public string getCategory(){  return Category; } public void setCategory(string c){ if(c<>null)category= String.escapeSingleQuotes(c); }
    
    public Datetime LastLoginDate{get;set;}
    List<Planning_Version__c> lstClosedPlanningVersion;
    public Set<string> lstAccountOption{get;set;}
    public Set<string> lstOpportunityOption{get;set;}
    public String sAccountText{get;
        set {
            if(sAccountText<>null)sAccountText = String.escapeSingleQuotes(sAccountText);
        }
    }
    public String sOpportunityText{get;
        set {
            if(sOpportunityText<>null)sOpportunityText = String.escapeSingleQuotes(sOpportunityText);
        }
    }
    
    map<string,set<string>> mapAccount;
    map<string,string> mapOpportunity;
    map<string,Fiscal_Year_Planning__c> mapFiscalSetting = new map<string,Fiscal_Year_Planning__c>();
    
    map<string,string> mapPlanningName;
    
    
    public List<Opportunity> lstOpportunity{get;set;}
    public pagereference retrieveData(){
        return null;
    }
    public List<wrapperOpportunity> PriorityOpportunity{get;set;}
    public Bookings_PrioritizationController(){ 
        
        
            dummyOpportunity = new Opportunity();
            setUser = new set<string>(); 
            if (Schema.sObjectType.User.fields.Id.isAccessible() && Schema.sObjectType.User.fields.Name.isAccessible()){
	            for(User u : [select Id,Name from User where Name <> null and isActive= true limit 100]){
	                setUser.add(u.Name);
	            }
            }
            Category ='Month'; 
            PriorityOpportunity = new List<wrapperOpportunity>();
            mapPlanningName = new map<string,string>();  
            getFilterOpportunity();
        
    }
    public List<Data> getData() {
        return chartData;
    }
    public class Data {
        public String name { get;set;}
        public Integer data1 { get; set; }
        public Data(String name, Integer data1) {
            this.name = name;
            this.data1 = data1;
        }
    }
    
    public class wrapperOpportunity{
        public opportunity opp{get;set;}
        public decimal oppConValue{get;set;}
        public string licolor{get;set;}      
        public string FiscalPeriodId{get;set;}        
        public string FiscalPeriodName{get;set;}        
        public string fQuarter{get;set;}
       
        public decimal FiscalAmount{get;set;}
        public wrapperOpportunity(opportunity opp, string FiscalPeriodId, string FiscalPeriodName, string fQuarter,decimal FiscalAmount,decimal oppConValue,string licolor){
            this.opp = opp;
            this.FiscalPeriodId = FiscalPeriodId;
            this.FiscalPeriodName = FiscalPeriodName;
            this.fQuarter = fQuarter;
            this.FiscalAmount = FiscalAmount;
            this.oppConValue = oppConValue;
            this.licolor = licolor;
        }
    }
    
    
    public void getFilterOpportunity(){
        
        
        try{
        string Inp_sAccountText = null;
        if(sAccountText <> null) {
            Inp_sAccountText = String.escapeSingleQuotes(sAccountText);
        }
        string Inp_sOpportunityText = null;
        if(sOpportunityText <> null) {
            Inp_sOpportunityText = String.escapeSingleQuotes(sOpportunityText);
        }
        
        string query = 'Select id,Name,Project_Start_Date__c,Deal_TCV__c,StageName,CloseDate,Deal_Duration__c,Account.Name,AccountId,Legacy__c,(select Id,Fiscal_Period__r.Fiscal_Quarter__c, Fiscal_Period__c,Fiscal_Period__r.Name,Amount__c from Planning_Models__r where Planning_Measure__r.Name = \'Revenue\') from Opportunity WHERE Deal_TCV__c <> NULL  AND isClosed = false  And StageName <> \'Sales Proration\'';
        if(strFromPlanYear <> null && strFromPlanYear <> 'All' && mapFiscalSetting.containsKey(strFromPlanYear)){
            Integer sYear = Integer.valueOf(mapFiscalSetting.get(strFromPlanYear).Name);
            query += ' and CALENDAR_YEAR(Project_Start_Date__c)  =: sYear and Project_Start_Date__c >= today ';
        }
        if(sAccountText <> null && sAccountText <> ''){
            query += ' and AccountId <> null and Account.Name =: Inp_sAccountText';
        }
        if(sOpportunityText <> null && sOpportunityText <> ''){
            query += ' and Name =: Inp_sOpportunityText';
            
        }
        
        if(OppStages <> null && OppStages.size()>0){
            set<string> setStages = new set<string>();
            for(string s : OppStages){ setStages.add(s);   }
            query += ' and stageName IN: setStages';
        }
        if(strAccOwner <> null && strAccOwner.trim() <> ''){
            query += ' and Account.Owner.Name =: strAccOwner ';
        }
        if(dummyOpportunity.BussinessUnit__c <> null){
        	String dummyOpportunityBussinessUnit =dummyOpportunity.BussinessUnit__c;
            query += ' and BussinessUnit__c = :dummyOpportunityBussinessUnit';
        }
        if(dummyOpportunity.Service_Line__c <> null){
        	String dummyOpportunityService_Line=dummyOpportunity.Service_Line__c;
            query += ' and Service_Line__c = :dummyOpportunityService_Line';
        }
        if(dummyOpportunity.Division__c <> null){
        	String dummyOpportunityDivision=dummyOpportunity.Division__c;
            query += ' and Division__c = :dummyOpportunityDivision';
        }
        query += ' order By Deal_TCV__c DESC';  
    
        List<Opportunity> lstOpp = new List<Opportunity>();
        try{
        	if(Opportunity.sObjectType.getDescribe().isAccessible()){
        		lstOpp = Database.Query(query); 
        	}
        	lstOpp = Database.Query(query); 
        }catch(Exception e){ ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR,e+'-'+query)); }
        
        
            
        PriorityOpportunity.clear();
        
        string FiscalPeriodId;
        string FiscalPeriodName;
        decimal FiscalAmount;
        map<string,decimal> mapviews = new map<string,decimal>();
        map<string,decimal> mapQviews = new map<string,decimal>();
        
        //apply multicurrency
        boolean isMultiCurrencyOrganization = userinfo.isMultiCurrencyOrganization();
        string DefaultCurrency = userinfo.getDefaultCurrency();
        if(DefaultCurrency == 'USD')userCurrencySign = '$';
        else if(DefaultCurrency == 'EUR')userCurrencySign = '€';
        else if(DefaultCurrency == 'INR')userCurrencySign = 'INR';
        else if(DefaultCurrency == 'CAD')userCurrencySign = '$';
        map<Id,string> mapcurrency = new map<Id,string>();
        set<Id> setOppCurrency = new set<Id>();
            
        for(Opportunity opp : lstOpp){ 
            setOppCurrency.add(opp.id);
        }
        if(isMultiCurrencyOrganization){
            mapcurrency = CurrencyConversion.opportunityCurrencyCode(setOppCurrency);
        }
        if(isMultiCurrencyOrganization){
            CurrencyConversion.Initialization();
            mapcurrency = CurrencyConversion.opportunityCurrencyCode(setOppCurrency);
        }
            
        for(Opportunity Opp: lstOpp){
            FiscalPeriodId = '';
            FiscalPeriodName = '';
            FiscalAmount = 0;
            string fyear = 'FY';
            fyear += opp.Project_Start_Date__c.year();
            fyear += 'P';
            fyear += opp.Project_Start_Date__c.month();
            string fQuarter = '';
            for(Planning_Model__c m : opp.Planning_Models__r){
                //system.debug('###:'+m.Fiscal_Period__r.Name +'=='+ fyear);
                if(m.Fiscal_Period__r.Name == fyear ){
                    FiscalPeriodId = m.Fiscal_Period__c;
                    FiscalPeriodName= m.Fiscal_Period__r.Name;
                    FiscalAmount= m.Amount__c;
                    if(isMultiCurrencyOrganization)CurrencyConversion.Convert(mapcurrency.get(opp.Id),DefaultCurrency,m.Amount__c);
                    mapviews.put(m.Fiscal_Period__r.Name,0);
                    mapQviews.put('FY'+opp.Project_Start_Date__c.year()+m.Fiscal_Period__r.Fiscal_Quarter__c,0);
                    fQuarter = m.Fiscal_Period__r.Fiscal_Quarter__c;    break;
                }
            }
            string licolor = '#005FB2';
            if(opp.Legacy__c == 'YES' && opp.StageName == 'Closed Won')licolor  = '#398F38';
            else if(opp.Legacy__c != 'YES' && opp.StageName == 'Closed Won')licolor  ='#008080';


            decimal oppconval = opp.Deal_TCV__c;
            if(isMultiCurrencyOrganization)CurrencyConversion.Convert(mapcurrency.get(opp.Id),DefaultCurrency,opp.Deal_TCV__c);
            PriorityOpportunity.add(new wrapperOpportunity(opp,FiscalPeriodId, FiscalPeriodName, fQuarter,FiscalAmount,oppconval,licolor));
        }
        
        for(wrapperOpportunity w: PriorityOpportunity){
            decimal t=0;
            if(mapviews.containsKey(FiscalPeriodName))t = mapviews.get(FiscalPeriodName);
            if( w.FiscalAmount <> null)
                t += w.FiscalAmount;
            mapviews.put(FiscalPeriodName,t);
            
            decimal t1=0;
            if(mapQviews.ContainsKey('FY'+w.opp.Project_Start_Date__c.year()+w.fQuarter))   t1 = mapQviews.get('FY'+w.opp.Project_Start_Date__c.year()+w.fQuarter);
            if( w.FiscalAmount <> null)
                t1 += w.FiscalAmount;
            
            mapQviews.put('FY'+w.opp.Project_Start_Date__c.year()+w.fQuarter,t1);
            
        }
        chartData = new List<Data>();
        if(category == 'Month'){
            for(string s : mapviews.keyset()){
                chartData.add(new Data(s,Integer.valueOf(mapviews.get(s))));
            }
        }
        else if(category == 'Quarter'){
            for(string s : mapQviews.keyset()){
                chartData.add(new Data(s,Integer.valueOf(mapQviews.get(s))));
            }
        }
        }
        catch(Exception e){  ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR,e+'-'+e.getLineNumber()));  }
        
    }


    public List<SelectOption> getOpportunityStages() {
        String[] OStages = new String[]{};
        List<SelectOption> options = new List<SelectOption>();
        if (Schema.sObjectType.OpportunityStage.fields.description.isAccessible() && Schema.sObjectType.OpportunityStage.fields.IsClosed.isAccessible()
        && Schema.sObjectType.OpportunityStage.fields.IsWon.isAccessible() && Schema.sObjectType.OpportunityStage.fields.MasterLabel.isAccessible()
        && Schema.sObjectType.OpportunityStage.fields.IsActive.isAccessible()){
	        for(OpportunityStage os : [select description,IsClosed,IsWon,MasterLabel,IsActive from OpportunityStage where isActive = true and IsClosed = false ]){
	            options.add(new SelectOption(os.MasterLabel,os.MasterLabel));
	            OStages.add(os.MasterLabel);
	        }
        }
        setOppStages(OStages);
        return options;
    }

    
    
    public List<SelectOption> getFromPlanYear() {
        List<SelectOption> options = new List<SelectOption>();
        List<Fiscal_Year_Planning__c> lstYear = new List<Fiscal_Year_Planning__c>();
        if (Schema.sObjectType.Fiscal_Year_Planning__c.fields.Id.isAccessible() && Schema.sObjectType.Fiscal_Year_Planning__c.fields.Name.isAccessible()
        && Schema.sObjectType.Fiscal_Year_Planning__c.fields.StartDate__c.isAccessible() && Schema.sObjectType.Fiscal_Year_Planning__c.fields.EndDate__c.isAccessible() ){
        	 lstYear = [select Id,Name,StartDate__c,EndDate__c from Fiscal_Year_Planning__c where Name <> null order by StartDate__c];
    	}
        options.add(new selectOption('All','All'));
        strFromPlanYear = 'All';
        if(lstYear.Size()>0){
	        for(Fiscal_Year_Planning__c fy : lstYear){
	            options.add(new selectOption(fy.Id,fy.Name));
	            mapFiscalSetting.put(fy.Id,fy);
	        }
        }
        return options;
    }

    public pagereference Export(){
        return page.SalesbookingExport;
    }
}