Demand Navigator/src/objects/Fiscal_Year_Planning__c.object
<CustomObject>
    <fields>
        <fullName>EndDate__c</fullName>
        <label>EndDate</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>StartDate__c</fullName>
        <label>StartDate</label>
        <type>Date</type>
    </fields>
    <label>FCST Fiscal Year List</label>
    <nameField>
        <label>Fiscal Year List Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>FCST Fiscal Year Lists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Demand Navigator/src/objects/Planning_Financial_Measure__c.object
<CustomObject>
    <label>FCST Planning Measure</label>
    <nameField>
        <label>Planning Measure Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>FCST Planning Measures</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Demand Navigator/src/objects/Planning_Model__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Comments__c</fullName>
        <label>Comments</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Planning_Measure__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Planning Measure</label>
        <referenceTo>Planning_Financial_Measure__c</referenceTo>
        <relationshipName>Planning_Models</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Planning_Version__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Planning Version</label>
        <referenceTo>Planning_Version__c</referenceTo>
        <relationshipName>Planning_Models</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>FCST Planning Model</label>
    <nameField>
        <displayFormat>M-{000000}</displayFormat>
        <label>Planning Model Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>FCST Planning Models</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Demand Navigator/src/objects/Planning_Version__c.object
<CustomObject>
    <fields>
        <fullName>Data_Entry_Closed_Date__c</fullName>
        <label>Data Entry Closed Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Data_Entry_Start_Date__c</fullName>
        <label>Data Entry Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Fiscal_Year_Planning__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Fiscal Year Planning</label>
        <referenceTo>Fiscal_Year_Planning__c</referenceTo>
        <relationshipName>Planning_Versions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Is_this_a_Budget_Planning_Version__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is this a Budget Planning Version?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>MonthName__c</fullName>
        <label>MonthName</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Planning_Version_Current_Period__c</fullName>
        <label>Planning Version Current Period</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Planning_Version_Fiscal_Year__c</fullName>
        <label>Planning Version Fiscal Year</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SequenceNo__c</fullName>
        <label>Sequence Number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Version_Status__c</fullName>
        <label>Version Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not Open</fullName>
                </value>
                <value>
                    <fullName>Open (Admin)</fullName>
                </value>
                <value>
                    <fullName>Open (User)</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>FCST Planning Version</label>
    <nameField>
        <label>Planning Version Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>FCST Planning Versions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Demand Navigator/src/classes/Test_Forecastera_Planning_Workbench.cls
@isTest(SeeAllData = true)
public with sharing class Test_Forecastera_Planning_Workbench{
    public testMethod static void UnitTest(){ 
        PageReference pageRef = Page.Forecastera_Planning_Workbench;
        Test.setCurrentPage(pageRef);
        Forecastera_Planning_Workbench con = new Forecastera_Planning_Workbench();
        con.setcUserName('testuser');
        con.setcUserRole('testrole');
        con.setSFDCInstance('na23');
        con.setsecurityToken('123');
        
        string user = con.getcUserName();
        string role = con.getcUserRole();
        string name = con.getSFDCInstance();
        string sec = con.getsecurityToken();
        
        con.gotohomepage();
        
        
        
        Date startDate = System.today();
        Date endDate = startDate.addDays(30);
        map<Integer,String> mapMonthString  = new map<Integer,String>();
        mapMonthString .put(1,'January');
        mapMonthString .put(2,'February');
        mapMonthString .put(3,'March');
        mapMonthString .put(4,'April');
        mapMonthString .put(5,'May');
        mapMonthString .put(6,'June');
        mapMonthString .put(7,'July');
        mapMonthString .put(8,'August');
        mapMonthString .put(9,'September');
        mapMonthString .put(10,'October');
        mapMonthString .put(11,'November');
        mapMonthString .put(12,'December');
        
        Date fstartDate = Date.newInstance(2001,1,1);
        Date fendDate = Date.newInstance(2001,12,31);
        Fiscal_Year_Planning__c fyp1 = new Fiscal_Year_Planning__c(Name = '2001',StartDate__c = fstartDate,EndDate__c = fendDate);
        if(Fiscal_Year_Planning__c.SObjectType.getDescribe().isCreateable()){
        insert fyp1;
        }
        
        List<Planning_Version__c>  lstVersion = new List<Planning_Version__c>();
        for(Integer i = 1;i<13;i++){
        
                lstVersion.add(
                    new Planning_Version__c(
                        Fiscal_Year_Planning__c = fyp1.Id,
                        Is_this_a_Budget_Planning_Version__c = false,
                        SequenceNo__c = i,
                        Data_Entry_Closed_Date__c= endDate ,
                        Data_Entry_Start_Date__c  = startDate ,
                        Version_Status__c= 'Closed',
                        Planning_Version_Fiscal_Year__c = ((2000+i)+''),
                        Planning_Version_Current_Period__c= i+'',
                        MonthName__c = mapMonthString.get(i)
                    ));
                    startDate  = endDate.addDays(1);
                    endDate = startDate.addDays(30);
        } 
        if(Planning_Version__c.SObjectType.getDescribe().isCreateable()){
        insert lstVersion;
        }
        
        Planning_Financial_Measure__c fm = new Planning_Financial_Measure__c(Name = 'Revenue Backlog');
        if(Planning_Financial_Measure__c.SObjectType.getDescribe().isCreateable()){
        insert fm;
        }
        System.currentPageReference().getParameters().put('P_strSavedStages', fm.Name);
        
        Planning_Model__c pm = new Planning_Model__c();
        
        pm.Amount__c = 100;
        pm.Comments__c = 'test';
        pm.Planning_Measure__c = fm.Id;
        pm.Planning_Version__c = lstVersion[10].Id;
        if(Planning_Model__c.SObjectType.getDescribe().isCreateable()){
        insert pm;
        }
        System.assertEquals(pm.Amount__c,100);
    }
   
}