Demand Navigator/src/objects/Fiscal_Year_Planning__c.object
<CustomObject>
    <fields>
        <fullName>EndDate__c</fullName>
        <label>EndDate</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>StartDate__c</fullName>
        <label>StartDate</label>
        <type>Date</type>
    </fields>
    <label>FCST Fiscal Year List</label>
    <nameField>
        <label>Fiscal Year List Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>FCST Fiscal Year Lists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Demand Navigator/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Budget_Planning_Version__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Budget Planning Version</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Planning_Version__c.Is_this_a_Budget_Planning_Version__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <infoMessage>Value does not exist or does not match filter criteria.</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Planning_Version__c</referenceTo>
        <relationshipLabel>Opportunities (Budget Planning Version)</relationshipLabel>
        <relationshipName>Opportunities2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Deal_Duration__c</fullName>
        <label>Deal Duration(months)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Deal_TCV__c</fullName>
        <label>Deal TCV $</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Planning_Version__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>FCST Planning Version</label>
        <referenceTo>Planning_Version__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project_Start_Date__c</fullName>
        <label>Project Start Date</label>
        <type>Date</type>
    </fields>
    <recordTypes>
        <fullName>Budget</fullName>
        <active>true</active>
        <businessProcess>Forecast Budget Process</businessProcess>
        <label>Budget</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Demand Navigator/src/objects/Planning_Version__c.object
<CustomObject>
    <fields>
        <fullName>Data_Entry_Closed_Date__c</fullName>
        <label>Data Entry Closed Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Data_Entry_Start_Date__c</fullName>
        <label>Data Entry Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Fiscal_Year_Planning__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Fiscal Year Planning</label>
        <referenceTo>Fiscal_Year_Planning__c</referenceTo>
        <relationshipName>Planning_Versions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Is_this_a_Budget_Planning_Version__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is this a Budget Planning Version?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>MonthName__c</fullName>
        <label>MonthName</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Planning_Version_Current_Period__c</fullName>
        <label>Planning Version Current Period</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Planning_Version_Fiscal_Year__c</fullName>
        <label>Planning Version Fiscal Year</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SequenceNo__c</fullName>
        <label>Sequence Number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Version_Status__c</fullName>
        <label>Version Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not Open</fullName>
                </value>
                <value>
                    <fullName>Open (Admin)</fullName>
                </value>
                <value>
                    <fullName>Open (User)</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>FCST Planning Version</label>
    <nameField>
        <label>Planning Version Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>FCST Planning Versions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Demand Navigator/src/classes/TEST_CurrencyConversion.cls
@isTest
public with sharing class TEST_CurrencyConversion{
    static testMethod void unitTest() {
        Date fstartDate = Date.newInstance(2001,1,1);
        Date fendDate = Date.newInstance(2001,12,31);
        Date startDate = System.today();
        Date endDate = startDate.addDays(30);
        Fiscal_Year_Planning__c fyp1 = new Fiscal_Year_Planning__c(Name = '2001',StartDate__c = fstartDate,EndDate__c = fendDate);
        if(Fiscal_Year_Planning__c.SObjectType.getDescribe().isCreateable()){
            
        insert fyp1;
         }
         List<Planning_Version__c>  lstVersion = new List<Planning_Version__c>();
            for(Integer i = 1;i<13;i++){
            
                    lstVersion.add(
                        new Planning_Version__c(
                            Fiscal_Year_Planning__c = fyp1.Id,
                            Is_this_a_Budget_Planning_Version__c = true,
                            SequenceNo__c = i,
                            Data_Entry_Closed_Date__c= endDate ,
                            Data_Entry_Start_Date__c  = startDate ,
                            Version_Status__c= 'Closed',
                            Planning_Version_Fiscal_Year__c = ((2000+i)+''),
                            Planning_Version_Current_Period__c= i+'',
                            MonthName__c = '5'
                        ));
                        startDate  = endDate.addDays(1);
                        endDate = startDate.addDays(30);
            } 
           if(Planning_Version__c.SObjectType.getDescribe().isCreateable()){
            
            insert lstVersion;
           }
        //Id devRecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Regular').getRecordTypeId();
        //Id devRecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Budget').getRecordTypeId();
        Account  Acc = new Account(Name = 'test account');
        if(Account.SObjectType.getDescribe().isCreateable()){
        insert Acc;
        }
        Date cd = date.newInstance(2001,6,1);
        Opportunity Opp = new Opportunity(
            name='Test Opp', 
            Deal_TCV__c = 100,
            accountId = Acc.Id,
            Deal_Duration__c  =12,
            StageName='Open',
            Project_Start_Date__c = date.today(),
            CloseDate=cd,
            //RecordTypeId=devRecordTypeId,
            Budget_Planning_Version__c=lstVersion[0].Id,
            Amount=1000000
        );  
        if(Opportunity.SObjectType.getDescribe().isCreateable()){      
        insert Opp;
        }
        system.assertNotEquals(opp.Id,null);
        set<Id> setOpp = new Set<Id>();
        setOpp.add(opp.Id);
        CurrencyConversion con = new CurrencyConversion();
        CurrencyConversion.Initialization();
        CurrencyConversion.opportunityCurrencyCode(setOpp);
        CurrencyConversion.Convert('USD','INR',100);
        
    }
}