Demand Navigator/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Planning_Version__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>FCST Planning Version</label>
        <referenceTo>Planning_Version__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Demand Navigator/src/objects/Planning_Model__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>Planning_Models</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Planning_Version__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Planning Version</label>
        <referenceTo>Planning_Version__c</referenceTo>
        <relationshipName>Planning_Models</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>FCST Planning Model</label>
    <nameField>
        <displayFormat>M-{000000}</displayFormat>
        <label>Planning Model Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>FCST Planning Models</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Demand Navigator/src/objects/Planning_Version__c.object
<CustomObject>
    <label>FCST Planning Version</label>
    <nameField>
        <label>Planning Version Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>FCST Planning Versions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Demand Navigator/src/classes/DemandForcecaseCSV.cls
public with sharing class DemandForcecaseCSV{

    public DemandForcecaseCSV() {
        string OppId = apexPages.currentPage().getParameters().get('Id');
        
        map<Id,String> mapVersion = new map<Id,string>();
        if (Schema.sObjectType.Opportunity.fields.Id.isAccessible() 
        && Schema.sObjectType.Planning_Model__c.fields.Id.isAccessible() 
        && Schema.sObjectType.Planning_Model__c.fields.Planning_Version__c.isAccessible() 
        && Schema.sObjectType.Planning_Version__c.fields.Name.isAccessible()  ){
            for(Opportunity opp : [select Id,(select Id,Planning_Version__c,Planning_Version__r.Name from Planning_Models__r) from Opportunity where Id=: oppId]){
                for(Planning_Model__c m : opp.Planning_Models__r){
                   mapVersion.put(m.Planning_Version__c, m.Planning_Version__r.Name);
                }
            }
        }
        input = '';
        
        for(Id vId :mapVersion.keySet()){
            DemandUtility dobj = new DemandUtility(oppId,vId );
            List<FiscalYear> lstTFModel = dobj.lstFModel;
            input += dobj.getDemandData(lstTFModel,mapVersion.get(vid));
        }
        
    }

    
    public string input{get;set;}
    
}